### ISSUE TITLE
How to disable auto-capitalize first letter? Default export `myFunction` is changed to `MyFunction`

### ISSUE THREAD

**Issue by vozaldi** [ZouYouShun/vscode-index-generator#11]
Thank you for the incredible plugin!

I had this issue which occurs when a filename started with lower case letter generating CamelCase variables instead of following its original naming.

From file  `myFunction.ts`

``` TypeScript
function myFunction() {
  console.log("Just a common function");
}

export default myFunction;
```

#### Generated file `index.ts` ❌

``` TypeScript
export { default as MyFunction } from "./myFunction";
```

#### Expected result for `index.ts` ✅

``` TypeScript
export { default as myFunction } from "./myFunction";
```

### Question

How can I disable auto CamelCase or is there any suggestion?

---

Thank you for your help.

**Comment by ZouYouShun** [comment]
Hi @vozaldi 

thanks for your question,

think that is a new feature, current that is not supported yet, we assume that is React default function, so we make that be uppercase.

I think that should be added that configure in settings,

I think we can provide a config for that

1. force default case => when generating file with `default export` use  `lowercase/CamelCase/Follow file name` to re-export.

**Comment by ZouYouShun** [comment]
<img width="921" alt="image" src="https://user-images.githubusercontent.com/5878538/222967382-59e67a8b-9439-4161-bbfc-f72e10a7d3d3.png">


Hi @vozaldi , that feature update in v2.1.0, remember upgrade and reload window if you not see that re export default case configuration

have a try 🧙

**Comment by vozaldi** [comment]
Thank you for your reply @ZouYouShun.

> think that is a new feature, current that is not supported yet, we assume that is React default function, so we make that be uppercase.

That's right, I also used React and this plugin really helped me tidying the component imports.

> I think we can provide a config for that
> 
> 1. `re-export default case` => when generating file with `default export` use  `lowerCamelCase/CamelCase/Follow file name` to re-export, default is `CamelCase`.

That's great solution, I'll give it a try. 🚀

Thank you for the update!
